using System;
using Gubbins.Enhance;
using UnityEngine;
using UnityEngine.Events;

namespace Gubbins.Events
{
    /// <summary>
    /// Serializable event bus that could set config on inspector.
    /// </summary>
    /// <remarks>
    /// Basically, a <see cref="IEvent"/> proxy.
    /// </remarks>
    [Serializable]
    public class SerializedEvent : MonoBehaviour, IEvent
    {
        /// <summary>
        /// UnityEvent for subscribe to event bus.
        /// </summary>
        [SerializeField] private UnityEvent m_Handlers;

        /// <summary>
        /// Handlers for wrap <see cref="m_Handlers"/>.
        /// </summary>
        private UnityEventHandler m_UnityEventHandlers;

        /// <summary>
        /// Proxy of even .
        /// </summary>
        private IEvent m_EventBus = new Event();

        /// <summary>
        /// Subscribe all unity events to event bus.
        /// </summary>
        private void Awake()
        {
            // The type name was generated by EventListener
            m_UnityEventHandlers = new UnityEventHandler(m_Handlers);
            m_EventBus.Subscribe(m_UnityEventHandlers);
        }

        /// <summary>
        /// Unsubscribe all unity events.
        /// </summary>
        private void OnDestroy() => m_EventBus?.Unsubscribe(m_UnityEventHandlers);

        /// <inheritdoc/>
        public void Subscribe(IEventHandler<Unit> handler) => m_EventBus?.Subscribe(handler);

        /// <inheritdoc/>
        public bool Unsubscribe(IEventHandler<Unit> handler) => m_EventBus?.Unsubscribe(handler) ?? false;

        /// <inheritdoc/>
        public void Clear() => m_Handlers.RemoveAllListeners();

        /// <inheritdoc/>
        public void Broadcast(Unit notification) => m_EventBus?.Broadcast(notification);

        /// <inheritdoc/>
        public void SubscribeWeakly(IWeakEventHandler<Unit> handler) => m_EventBus?.SubscribeWeakly(handler);
    }
}