// Copyright ©2024 Gatongone
// Author: Gatongone
// Email: gatongone@gmail.com
// Created On: 2024/05/26-13:53:06
// Github: https://github.com/Gatongone

using System;
using Gubbins.Enhance;
using UnityEngine;
using UnityEngine.Events;

namespace Gubbins.Events
{
    /// <summary>
    /// Serializable event bus that could set config on inspector.
    /// </summary>
    /// <remarks>
    /// Basically, it is a <see cref="IEventBus"/> proxy.
    /// </remarks>
    [Serializable]
    public class SerializedEvent : MonoBehaviour, IEvent
    {
        private const TypeKind DEFAULT_TYPE_KIND = TypeKind.Implementation | TypeKind.Newable | TypeKind.Class;

        [SerializeField, TypeFrom(typeof(IEvent), DEFAULT_TYPE_KIND, typeof(SerializedEvent), typeof(Event))]
        private SerializedType m_Event;

        [SerializeField] private UnityEvent m_Handlers;

        /// <summary>
        /// Handlers for wrap <see cref="m_Handlers"/>.
        /// </summary>
        private UnityEventHandler m_UnityEventHandlers;

        /// <summary>
        /// Proxy of event bus.
        /// </summary>
        private IEvent m_EventBus;

        private void Awake()
        {
            // if (m_Category.Type == null || m_Event.Type == null) return;
            //
            // // The type name was generated by EventListener
            // var typeName = m_Event.Type.Name;
            // var context = Category.GetCategory(m_Category).Context;
            // m_EventBus = context.Resolve<IEventBus>(typeName);
            //
            // if (m_EventBus == null && m_Event.Type.IsNewable(out var newer))
            // {
            //     m_EventBus = (IEventBus) newer.New();
            //     context.Resolve<IDependenciesRegistry>()
            //            .Register(m_EventBus)
            //            .BindTo(m_Event)
            //            .BindTo<IEventBus, IEventSubscriable, IEventBroadcastable, IWeakEventSubscriable>()
            //            .BindTo<IEventBus<Unit>, IEventBroadcastable<Unit>, IEventSubscriable<Unit>>()
            //            .WithKey(typeName)
            //            .AsSingleton();
            // }
            // else
            // {
            //     throw new ArgumentException("Event required null value.");
            // }
            //
            // m_UnityEventHandlers = new UnityEventHandler(m_Handlers);
            // m_EventBus.Subscribe(m_UnityEventHandlers);
        }

        /// <summary>
        /// Unsubscribe all unity events.
        /// </summary>
        private void OnDestroy() => m_EventBus?.Unsubscribe(m_UnityEventHandlers);

        /// <inheritdoc/>
        public void Subscribe(IEventHandler<Unit> handler) => m_EventBus?.Subscribe(handler);

        /// <inheritdoc/>
        public bool Unsubscribe(IEventHandler<Unit> handler) => m_EventBus?.Unsubscribe(handler) ?? false;

        /// <inheritdoc/>
        public void Clear() => m_EventBus?.Clear();

        /// <inheritdoc/>
        public void Broadcast(Unit notification) => m_EventBus?.Broadcast(notification);

        /// <inheritdoc/>
        public void SubscribeWeakly(IWeakEventHandler<Unit> handler) => m_EventBus?.SubscribeWeakly(handler);
    }
}